# 读
spring:
  datasource:
    read:
      url: jdbc:mysql://X.X.X.X:port/titan?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

# 写
spring:
  datasource:
    write:
      url: jdbc:mysql://X.X.X.X:port/titan?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver